            <div id="footer">
            	<div class="footer_copyright">
                    <?php
                        $author = UTIL::Load_Content('author', 'static');

                        $searches = array('{author}');
                        $replaces = array($author);
                        $arguments = array($searches, $replaces);
                        $copyright_template = UTIL::Fetch_Template('copyright', $arguments);

                        echo $copyright_template;
                    ?>
                </div>
            </div>
