		            <div id="languages">
		            	<?php
		            		$my_route = UTIL::Denormalize_Route(MVC::Get_Route('this'));

		            		if ($my_route === 'root')
		            			$my_route = '';

							$all_langs = LANG::Get('all');

		            		foreach ($all_langs as $index => $language)
		            		{
		            			if ($language === LANG::Get('this'))
		            				$active = 'active_language';
		            			else
		            				$active = '';

		            			echo '<a href="/'. $language . '/' . 
		            							   $my_route . '" class="' . 
		            							   $active . '">' . 
		            							   strtoupper($language) . '</a>';

		            			if ($index < (count(LANG::Get('all')) - 1))
		            				echo ' | ';
		            		}
		            	?>
		            </div>
