<!DOCTYPE html>
<html lang="<?=LANG::Get('this'); ?>">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="Cache-control" content="public">
        <meta name="robots" content="index, nofollow">
        <meta name="description" content="{os_name} - Meta-OS">
        <meta name="keywords" content="meta-os,ecosystem,platform,framework,cloud,secure,simple">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" type="image/png" href="/site/pix/greyos_icon.png">
        <link rel="stylesheet" href="/site/css/main.css">
        <link href="https://fonts.googleapis.com/css?family=Ubuntu:400,500&subset=latin,greek" rel="stylesheet" type="text/css">
        <title><?=UTIL::Load_Content('title', 'static');?></title>
    </head>
    <body>
        <div id="greyos">
        <?php
            UTIL::Load_Section('header');
            
            // Include the JS Compactor to optimize and load all JS extensions on reload (Optional - Use for speed at release)
            require('site/php/js_compactor.php');
            
            $this_route = MVC::Get_Route('this');
            
            if ($this_route === false)
                require('framework/errors/404.phtml');
            else
            {
                if ($this_route === 'root')
                {
                    /*
                        [!] ATTENTION [!]
                        If you use the "JS Compactor" do not call "Autoload_Extensions()" and "Load_Extension(..., 'js')" API for any pre-loaded JS
                        If you do so, you will end up with duplicated non-optimized JS extensions with strange behavior.
                    */
                    //UTIL::Autoload_Extensions();
                    
                    require('site/php/ext_loader.php');
                    
                    MVC::Go_To($this_route);
                ?>
                    <script type="module">
                        import Hyperbeam, { getRegionInfo } from "https://unpkg.com/@hyperbeam/web@latest/dist/index.js";

                        const regionInfo = await getRegionInfo();
                        
                        window.hyperbeam = Hyperbeam;
                    </script>
                    <script src="/framework/extensions/js/user/ace/src/ace-min.js"></script>
                    <script src="/framework/extensions/js/user/ace/src/ext-language_tools.js"></script>
                    <script src="/framework/extensions/js/user/ace/src/ext-settings_menu.js"></script>
                    <script src="/site/js/boot.js" defer></script>
                <?php
                }
                else
                {
                    $args = '';
                    
                    MVC::Go_To($this_route, $args);
                }
                ?>
            <?php
            }
            
            unset($this_route);
        ?>
        </div>
    </body>
</html>
