<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="Cache-control" content="public">
        <meta name="robots" content="index, nofollow">
        <meta name="description" content="{os_name} - Meta-OS">
        <meta name="keywords" content="meta-os,ecosystem,platform,framework,cloud,secure,simple">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" type="image/png" href="/site/pix/greyos_icon.png">
        <link rel="stylesheet" href="/site/css/main.css">
        <link href="https://fonts.googleapis.com/css?family=Ubuntu:400,500&subset=latin,greek" rel="stylesheet" type="text/css">
        <!-- [*] Uncomment the line below to load all JS extensions in one file after using the JS Compactor [*] -->
        <!-- <script src="/site/js/all_ext_min.js"></script> -->
        <title><?=UTIL::Load_Content('title', 'static');?></title>
    </head>
    <body>
        <div id="greyos">
        <?php
            UTIL::Load_Section('header');
            
            $this_route = MVC::Get_Route('this');
            
            if ($this_route === false)
                require('framework/errors/404.phtml');
            else
            {
                UTIL::Autoload_Extensions();
                
                require('site/php/ext_loader.php');
                
                if ($this_route === 'root')
                    MVC::Go_To($this_route);
                else
                {
                    $args = '';
                    
                    MVC::Go_To($this_route, $args);
                }
            }
            
            unset($this_route);
        ?>
            <script src="/framework/extensions/js/user/ace/src/ace-min.js"></script>
            <script src="/framework/extensions/js/user/ace/src/ext-language_tools.js"></script>
            <script src="/framework/extensions/js/user/ace/src/ext-settings_menu.js"></script>
            <script src="/site/js/boot.js"></script>
        </div>
    </body>
</html>
