<?php

    /*
    
        GreyOS - ALPHA CMS
        
        Version: 10.0
        
        File name: admin_content.phtml
        Description: This file contains the admin content HTML.
        
        Coded by George Delaportas (G0D)
        
        GreyOS
        Copyright © 2013
    
    */
    
    
    
    $my_lang = ALPHA_CMS::Get_Language();
    
    $contents = array();
    $records = array();
    
    echo ALPHA_CMS::Load_Content('all_content', 'content', $my_lang);
    
    if (!empty($_POST['del_content_id']) && $_SESSION['ALPHA_CMS_USER_TYPE'] < 2)
    {
    
        $result = ALPHA_CMS::Execute_SQL_Command('SELECT `is_protected` 
                                                  FROM `alpha_content` 
                                                  WHERE `id` = ' . mysqli_real_escape_string($db_con, $_POST['del_content_id']), 1);
        
        if ($result[0][0] == 1)
        {
        
            if ($_SESSION['ALPHA_CMS_USER'] == 'admin')
            {
            
                $result =  ALPHA_CMS::Execute_SQL_Command('UPDATE `alpha_menu` 
                                                           INNER JOIN `alpha_content` 
                                                           ON `alpha_content`.`page` = `alpha_menu`.`menu_link` 
                                                           SET `menu_link` = \'\' 
                                                           WHERE `alpha_content`.`id` = ' . 
                                                           mysqli_real_escape_string($db_con, $_POST['del_content_id']), 1);

                $result = ALPHA_CMS::Delete_Content($_POST['del_content_id']);

                $rest_routes_result = ALPHA_CMS::Execute_SQL_Command('SELECT `is_route` 
                                                                      FROM `alpha_content` 
                                                                      WHERE (`is_route` = 1 AND 
                                                                             `page` = ' . '\'' . 
                                                                      mysqli_real_escape_string($db_con, $_POST['del_page']) . '\')', 1);

                if (empty($rest_routes_result))
                {

                    if (file_exists(realpath('framework/mvc/models/') . '/' . str_replace('-', '_', $_POST['del_page']) . '.php'))
                    {

                        $file_result = unlink(realpath('framework/mvc/models/') . '/' . str_replace('-', '_', $_POST['del_page']) . '.php');

                    }

                    if (file_exists(realpath('framework/mvc/views/') . '/' . str_replace('-', '_', $_POST['del_page']) . '.phtml'))
                    {

                        $file_result = unlink(realpath('framework/mvc/views/') . '/' . str_replace('-', '_', $_POST['del_page']) . '.phtml');

                    }

                }
            
            }
        
        }
        
        else
        {
        
            $result =  ALPHA_CMS::Execute_SQL_Command('UPDATE `alpha_menu` 
                                                       INNER JOIN `alpha_content` 
                                                       ON `alpha_content`.`page` = `alpha_menu`.`menu_link` 
                                                       SET `menu_link` = \'\' 
                                                       WHERE `alpha_content`.`id` = ' . 
                                                       mysqli_real_escape_string($db_con, $_POST['del_content_id']), 1);

            $result = ALPHA_CMS::Delete_Content($_POST['del_content_id']);

            $rest_routes_result = ALPHA_CMS::Execute_SQL_Command('SELECT `is_route` 
                                                                  FROM `alpha_content` 
                                                                  WHERE (`is_route` = 1 AND 
                                                                         `page` = ' . '\'' . 
                                                                  mysqli_real_escape_string($db_con, $_POST['del_page']) . '\')', 1);

            if (empty($rest_routes_result))
            {

                if (file_exists(realpath('framework/mvc/models/') . '/' . str_replace('-', '_', $_POST['del_page']) . '.php'))
                {

                    $file_result = unlink(realpath('framework/mvc/models/') . '/' . str_replace('-', '_', $_POST['del_page']) . '.php');

                }

                if (file_exists(realpath('framework/mvc/views/') . '/' . str_replace('-', '_', $_POST['del_page']) . '.phtml'))
                {

                    $file_result = unlink(realpath('framework/mvc/views/') . '/' . str_replace('-', '_', $_POST['del_page']) . '.phtml');

                }

            }
        
        }
        
        $_POST['del_content_id'] = 0;
    
    }
    
    $records = ALPHA_CMS::Execute_SQL_Command('SELECT COUNT(*) 
                                               FROM `alpha_content`', 1);
    
    ALPHA_CMS::Load_Extension('search_bar', 'php');
    ALPHA_CMS::Load_Extension('gutenberg', 'php');
    ALPHA_CMS::Load_Extension('ckeditor', 'js');
    ALPHA_CMS::Load_Extension('ckfinder', 'ajax');

?>



<script type="text/javascript">

    // Order
    function Do_Order()
    {
    
        document.getElementById('admin_form_dhtml').submit();
        
        return 1;
    
    }
    
    // Show content details
    function Show_Content_Details(content_id)
    {
    
        var ajax = new bull();
        var contents_content = null;
        
        if (content_id === null || content_id <= 0)
            return 0;
        
        contents_content = ajax.response('/cms/site/back_end/php/actions/content_details.php', 
                                         'content=1&content_id=' + content_id + 
                                         '&lang_code=<?php echo $my_lang; ?>', 1);
        
        document.getElementById('contents_details').innerHTML = contents_content;
        
        document.getElementById('contents_details').style.top = document.body.clientTop + 420 + 'px';
        document.getElementById('contents_details').style.left = (document.body.clientWidth / 2) - 415 + 'px';
        
        document.getElementById('contents_shadow').style.width = screen.width + 'px';
        document.getElementById('contents_shadow').style.height = screen.height + 'px';
        
        document.getElementById('contents_shadow').style.display = 'block';
        document.getElementById('contents_details').style.display = 'block';
        
        return 1;
    
    }
    
    // New content
    function New_Content()
    {
    
        var ajax = new bull();
        var contents_content = null;
        
        contents_content = ajax.response('/cms/site/back_end/php/actions/new_content.php', 
                                         'new=1' + '&lang_code=<?php echo $my_lang; ?>', 1);
        
        document.getElementById('contents_details').innerHTML = contents_content;
        
        document.getElementById('contents_details').style.top = document.body.clientTop + 420 + 'px';
        document.getElementById('contents_details').style.left = (document.body.clientWidth / 2) - 415 + 'px';
        
        document.getElementById('contents_shadow').style.width = screen.width + 'px';
        document.getElementById('contents_shadow').style.height = screen.height + 'px';
        
        Show_CKEditor('insert_content');
        
        document.getElementById('contents_shadow').style.display = 'block';
        document.getElementById('contents_details').style.display = 'block';
        
        return 1;
    
    }
    
    // Edit content
    function Edit_Content(content_id)
    {
    
        var ajax = new bull();
        var contents_content = null;
        
        if (content_id === null || content_id <= 0)
            return 0;
        
        contents_content = ajax.response('/cms/site/back_end/php/actions/edit_content.php', 
                                         'edit=1&content_id=' + content_id + '&lang_code=<?php echo $my_lang; ?>', 1);
        
        document.getElementById('contents_details').innerHTML = contents_content;
        
        document.getElementById('contents_details').style.top = document.body.clientTop + 420 + 'px';
        document.getElementById('contents_details').style.left = (document.body.clientWidth / 2) - 415 + 'px';
        
        document.getElementById('contents_shadow').style.width = screen.width + 'px';
        document.getElementById('contents_shadow').style.height = screen.height + 'px';
        
        Show_CKEditor('edit_content');
        
        document.getElementById('contents_shadow').style.display = 'block';
        document.getElementById('contents_details').style.display = 'block';
        
        return 1;
    
    }

    // Delete content
    function Delete_Content(content_id)
    {
    
        var ajax = new bull();
        var contents_content = null;
        
        if (content_id === null || content_id <= 0)
            return 0;
        
        contents_content = ajax.response('/cms/site/back_end/php/actions/control/content_delete.php', 
                                         'delete=1&content_id=' + content_id + '&lang_code=<?php echo $my_lang; ?>', 1);
        
        document.getElementById('contents_details').innerHTML = contents_content;
        
        document.getElementById('contents_details').style.minWidth = '500px';
        document.getElementById('contents_details').style.width = '500px';
        document.getElementById('contents_details_area').style.width = '500px';
        document.getElementById('contents_details').style.top = document.body.clientTop + 420 + 'px';
        document.getElementById('contents_details').style.left = (document.body.clientWidth / 2) - 250 + 'px';
        
        document.getElementById('contents_shadow').style.width = screen.width + 'px';
        document.getElementById('contents_shadow').style.height = screen.height + 'px';
        
        document.getElementById('contents_shadow').style.display = 'block';
        document.getElementById('contents_details').style.display = 'block';
        
        return 1;
    
    }
    
    // Insert new content
    function Insert_This_Content()
    {
    
        var objects_values = new Array();
        var result = null;
        
        objects_values[0] = CKEDITOR.instances['insert_content'].getData();
        objects_values[1] = 'insert_page';
        objects_values[2] = 'insert_keywords';
        objects_values[3] = 'insert_select_lang_code';
        objects_values[4] = 'insert_protected_content';
        objects_values[5] = 'insert_route';
        
        result = Form_Validator('insert_content_form', objects_values);
        
        if (result === false)
            return 0;
        
        document.getElementById('admin_form_dhtml').submit();
        
        return 1;
    
    }
    
    // Update this content
    function Update_This_Content(content_id)
    {
    
        var objects_values = new Array();
        var result = null;
        
        if (content_id === null || content_id <= 0)
            return 0;
        
        objects_values[0] = content_id;
        objects_values[1] = CKEDITOR.instances['edit_content'].getData();
        objects_values[2] = 'edit_page';
        objects_values[3] = 'edit_keywords';
        objects_values[4] = 'edit_select_lang_code';
        objects_values[5] = 'edit_protected_content';
        objects_values[6] = 'edit_route';
        
        result = Form_Validator('update_content_form', objects_values);
        
        if (result === false)
            return 0;
        
        document.getElementById('admin_form_dhtml').submit();
        
        return 1;
    
    }
    
    // Delete this content
    function Delete_This_Content(content_id, page)
    {
    
        document.getElementById('del_content_id').value = content_id;
        document.getElementById('del_page').value = page;
        
        document.getElementById('admin_form_dhtml').submit();
        
        return 1;
    
    }
    
    // Close content details
    function Close_Content_Details()
    {
    
        document.getElementById('contents_shadow').style.display = 'none';
        document.getElementById('contents_details').style.display = 'none';
        
        document.getElementById('contents_details').style.minWidth = '820px';
        document.getElementById('contents_details').style.width = '820px';
        document.getElementById('contents_details_area').style.width = '820px';
        
        return 1;
    
    }
    
    // Show CKEditor
    function Show_CKEditor(obj_id)
    {
    
        var instance = null;
        
        instance = CKEDITOR.instances[obj_id];
        
        if(instance)
            CKEDITOR.remove(instance);
        
        <?php if ($my_lang == 'gr'): ?>
        CKEDITOR.config.language = 'el';
        <?php else: ?>
        CKEDITOR.config.language = '<? echo $my_lang; ?>';
        <?php endif; ?>
        
        CKEDITOR.config.height = '260px';
        CKEDITOR.config.resize_minWidth = '820px';
        CKEDITOR.config.resize_minHeight = '260px';
        
        CKEDITOR.replace(obj_id, 
        {
        
            filebrowserBrowseUrl: '/tmp/', 
            filebrowserImageBrowseUrl: '/tmp/', 
            filebrowserFlashBrowseUrl: '/tmp/', 
            filebrowserUploadUrl: '/framework/extensions/js/ckfinder/core/connector/php' + 
                                  '/connector.php?command=QuickUpload&type=Files&currentFolder=/tmp/', 
            filebrowserImageUploadUrl: '/framework/extensions/js/ckfinder/core/connector/php' + 
                                       '/connector.php?command=QuickUpload&type=Files&currentFolder=/tmp/', 
            filebrowserFlashUploadUrl : '/framework/extensions/js/ckfinder/core/connector/php' + 
                                        '/connector.php?command=QuickUpload&type=Flash'
        
        });
        
        return 1;
    
    }

</script>

<div class="class_content_area">
    <div id="contents_area">
        <input id="del_content_id" name="del_content_id" type="hidden" value="" />
        <input id="del_page" name="del_page" type="hidden" value="" />
        <div id="table_controls">
            <div id="contents_controls">
                <div class="class_records">
                    <?php echo ALPHA_CMS::Load_Content('records', 'content', $my_lang) . ' ' . $records[0][0]; ?>
                </div>
                <?php if ($_SESSION['ALPHA_CMS_USER_TYPE'] < 2): ?>
                <input id="new_content" onclick="New_Content();" class="button" 
                       type="button" value="<?php echo ALPHA_CMS::Load_Content('new_content_label', 'content', $my_lang); ?>" />
                <?php else: ?>
                <input id="new_content" onclick="New_Content();" class="button" style="color: #BFBFBF;" disabled 
                       type="button" value="<?php echo ALPHA_CMS::Load_Content('new_content_label', 'content', $my_lang); ?>" />
                <?php endif; ?>
                <?php
               
                    if ($records[0][0] > 0)
                        Search_Bar::Show();
                    
                    else
                        Search_Bar::Show(false);
                
                ?>
                <div id="sorting">
                    <div id="sort_label"><?php echo ALPHA_CMS::Load_Content('sort_label', 'content', $my_lang); ?>&nbsp;</div>
                    <?php 
                    
                        if ($records[0][0] < 2)
                            echo '<select id="sort_type" name="sort_type" disabled>';
                        
                        else
                            echo '<select id="sort_type" name="sort_type" onchange="Do_Order();">';
                        
                        if (empty($_POST['sort_type']) || $_POST['sort_type'] == 'ASC')
                        {

                            echo '<option selected value="ASC">' . 
                                 ALPHA_CMS::Load_Content('asc_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="DESC">' . 
                                 ALPHA_CMS::Load_Content('desc_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['sort_type'] == 'DESC')
                        {

                            echo '<option value="ASC">' . 
                                 ALPHA_CMS::Load_Content('asc_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="DESC">' . 
                                 ALPHA_CMS::Load_Content('desc_label', 'content', $my_lang) . 
                                 '</option>';

                        }
                        
                        echo '</select>';
                    
                    ?>
                </div>
                <div id="ordering">
                    <div id="order_label"><?php echo ALPHA_CMS::Load_Content('order_label', 'content', $my_lang); ?>&nbsp;</div>
                    <?php
                    
                        if ($records[0][0] < 2)
                            echo '<select id="order_type" name="order_type" disabled>';
                        
                        else
                            echo '<select id="order_type" name="order_type" onchange="Do_Order();">';
                        
                        if (empty($_POST['order_type']) || $_POST['order_type'] == 'id')
                        {

                            echo '<option selected value="id">' . 
                                 ALPHA_CMS::Load_Content('id_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="page">' . 
                                 ALPHA_CMS::Load_Content('page_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="content">' . 
                                 ALPHA_CMS::Load_Content('content_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="keywords">' . 
                                 ALPHA_CMS::Load_Content('page_keywords_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="lang_id">' . 
                                 ALPHA_CMS::Load_Content('lang_code_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="is_protected">' . 
                                 ALPHA_CMS::Load_Content('protected_content_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="is_route">' . 
                                 ALPHA_CMS::Load_Content('route_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'page')
                        {

                            echo '<option value="id">' . 
                                 ALPHA_CMS::Load_Content('id_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="page">' . 
                                 ALPHA_CMS::Load_Content('page_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="content">' . 
                                 ALPHA_CMS::Load_Content('content_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="keywords">' . 
                                 ALPHA_CMS::Load_Content('page_keywords_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="lang_id">' . 
                                 ALPHA_CMS::Load_Content('lang_code_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="is_protected">' . 
                                 ALPHA_CMS::Load_Content('protected_content_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="is_route">' . 
                                 ALPHA_CMS::Load_Content('route_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'content')
                        {

                            echo '<option value="id">' . 
                                 ALPHA_CMS::Load_Content('id_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="page">' . 
                                 ALPHA_CMS::Load_Content('page_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="content">' . 
                                 ALPHA_CMS::Load_Content('content_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="keywords">' . 
                                 ALPHA_CMS::Load_Content('page_keywords_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="lang_id">' . 
                                 ALPHA_CMS::Load_Content('lang_code_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="is_protected">' . 
                                 ALPHA_CMS::Load_Content('protected_content_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="is_route">' . 
                                 ALPHA_CMS::Load_Content('route_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'keywords')
                        {

                            echo '<option value="id">' . 
                                 ALPHA_CMS::Load_Content('id_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="page">' . 
                                 ALPHA_CMS::Load_Content('page_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="content">' . 
                                 ALPHA_CMS::Load_Content('content_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="keywords">' . 
                                 ALPHA_CMS::Load_Content('page_keywords_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="lang_id">' . 
                                 ALPHA_CMS::Load_Content('lang_code_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="is_protected">' . 
                                 ALPHA_CMS::Load_Content('protected_content_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="is_route">' . 
                                 ALPHA_CMS::Load_Content('route_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'lang_id')
                        {

                            echo '<option value="id">' . 
                                 ALPHA_CMS::Load_Content('id_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="page">' . 
                                 ALPHA_CMS::Load_Content('page_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="content">' . 
                                 ALPHA_CMS::Load_Content('content_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="keywords">' . 
                                 ALPHA_CMS::Load_Content('page_keywords_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="lang_id">' . 
                                 ALPHA_CMS::Load_Content('lang_code_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="is_protected">' . 
                                 ALPHA_CMS::Load_Content('protected_content_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="is_route">' . 
                                 ALPHA_CMS::Load_Content('route_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'is_protected')
                        {

                            echo '<option value="id">' . 
                                 ALPHA_CMS::Load_Content('id_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="page">' . 
                                 ALPHA_CMS::Load_Content('page_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="content">' . 
                                 ALPHA_CMS::Load_Content('content_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="keywords">' . 
                                 ALPHA_CMS::Load_Content('page_keywords_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="lang_id">' . 
                                 ALPHA_CMS::Load_Content('lang_code_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="is_protected">' . 
                                 ALPHA_CMS::Load_Content('protected_content_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="is_route">' . 
                                 ALPHA_CMS::Load_Content('route_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'is_route')
                        {

                            echo '<option value="id">' . 
                                 ALPHA_CMS::Load_Content('id_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="page">' . 
                                 ALPHA_CMS::Load_Content('page_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="content">' . 
                                 ALPHA_CMS::Load_Content('content_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="keywords">' . 
                                 ALPHA_CMS::Load_Content('page_keywords_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="lang_id">' . 
                                 ALPHA_CMS::Load_Content('lang_code_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="is_protected">' . 
                                 ALPHA_CMS::Load_Content('protected_content_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="is_route">' . 
                                 ALPHA_CMS::Load_Content('route_label', 'content', $my_lang) . 
                                 '</option>';

                        }
                        
                        echo '</select>';
                    
                    ?>
                </div>
            </div>
        </div>
        <div id="contents_content">
            <table id="contents_table">
                <tr class="class_table_header">
                    <td><?php echo ALPHA_CMS::Load_Content('id_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('page_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('content_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('page_keywords_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('lang_code_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('protected_content_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('route_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('options_label', 'content', $my_lang); ?></td>
                </tr>
            <?php
            
                if (!empty($_POST['search_bar']))
                {
                
                    if (empty($_POST['order_type']) || empty($_POST['sort_type']))
                        $contents = Search_Bar::Search('content', $_POST['search_bar']);
                    
                    else
                        $contents = Search_Bar::Search('content', $_POST['search_bar'], $_POST['order_type'], $_POST['sort_type']);
                
                    if (is_bool($contents))
                        exit;
                    
                    if (empty($_SESSION['G_RESET_SEARCH']))
                    {
                    
                        Gutenberg('content', $contents, 22, $_POST['offset'], 1);
                        
                        $_SESSION['G_RESET_SEARCH'] = 1;
                        $_SESSION['PREVIOUS_SEARCH_STR'] = $_POST['search_bar'];
                    
                    }
                    
                    else
                    {
                    
                        if ($_POST['search_bar'] != $_SESSION['PREVIOUS_SEARCH_STR'])
                            Gutenberg('content', $contents, 22, $_POST['offset'], 1);
                        
                        else
                            Gutenberg('content', $contents, 22, $_POST['offset']);
                        
                        $_SESSION['G_RESET_OFFSET'] = 1;
                        $_SESSION['PREVIOUS_SEARCH_STR'] = $_POST['search_bar'];
                    
                    }
                
                }
                
                else
                {
                
                    if (empty($_POST['order_type']) || empty($_POST['sort_type']))
                    {

                        $contents = ALPHA_CMS::Execute_SQL_Command('SELECT `alpha_content`.`id`, `page`, `content`, 
                                                                    `keywords`, `lang_code`, 
                                                                    `alpha_content`.`is_protected`, `is_route` 
                                                                    FROM `alpha_content` 
                                                                    INNER JOIN `alpha_languages` 
                                                                    ON `alpha_content`.`lang_id` = `alpha_languages`.`id` 
                                                                    ORDER BY `alpha_content`.`id` ASC', 1);

                    }

                    else
                    {

                        $contents = ALPHA_CMS::Execute_SQL_Command('SELECT `alpha_content`.`id`, `page`, `content`, 
                                                                    `keywords`, `lang_code`, 
                                                                    `alpha_content`.`is_protected`, `is_route` 
                                                                    FROM `alpha_content` 
                                                                    INNER JOIN `alpha_languages` 
                                                                    ON `alpha_content`.`lang_id` = `alpha_languages`.`id` 
                                                                    ORDER BY `' . $_POST['order_type'] . '` ' . $_POST['sort_type'], 1);

                    }
                    
                    if (is_bool($contents))
                        exit;
                    
                    if (!empty($_SESSION['G_RESET_OFFSET']))
                    {
                    
                        Gutenberg('content', $contents, 22, $_POST['offset'], 1);
                        
                        $_SESSION['G_RESET_OFFSET'] = 0;
                    
                    }
                    
                    else
                        Gutenberg('content', $contents, 22, $_POST['offset']);
                    
                    $_SESSION['G_RESET_SEARCH'] = 0;
                
                }
            
            ?>
    </div>
    <div id="contents_details"></div>
    <div id="contents_shadow"></div>
</div>

<div style="display: none;">
    <textarea id="init_content" class="ckeditor" rows="1" cols="1"></textarea>
</div>
