<?php

    /*
    
        GreyOS - ALPHA CMS
        
        Version: 10.0
        
        File name: admin_users.phtml
        Description: This file contains the admin users HTML.
        
        Coded by George Delaportas (G0D)
        
        GreyOS
        Copyright © 2013
    
    */
    
    
    
    $my_lang = ALPHA_CMS::Get_Language();
    
    $users = array();
    $records = array();
    
    echo ALPHA_CMS::Load_Content('users_content', 'content', $my_lang);
    
    if (!empty($_POST['del_user_id']) && $_SESSION['ALPHA_CMS_USER_TYPE'] < 1)
    {
    
        if ($_POST['del_user_id'] != 1 && $_SESSION['ALPHA_CMS_USER_ID'] != $_POST['del_user_id'])
            ALPHA_CMS::Delete_User($_POST['del_user_id']);
        
        $_POST['del_user_id'] = 0;
    
    }
    
    $records = ALPHA_CMS::Execute_SQL_Command('SELECT COUNT(*) 
                                               FROM `alpha_users`', 1);
    
    ALPHA_CMS::Load_Extension('search_bar', 'php');
    ALPHA_CMS::Load_Extension('gutenberg', 'php');

?>

<script type="text/javascript">

    // Order
    function Do_Order()
    {
    
        document.getElementById('admin_form_dhtml').submit();
        
        return 1;
    
    }
    
    // New user
    function New_User()
    {
    
        var ajax = new bull();
        var users_content = null;
        
        users_content = ajax.response('/cms/site/back_end/php/actions/new_user.php', 
                                      'new=1' + '&lang_code=<?php echo $my_lang; ?>', 1);
        
        document.getElementById('users_details').innerHTML = users_content;
        
        document.getElementById('users_details').style.top = document.body.clientTop + 420 + 'px';
        document.getElementById('users_details').style.left = (document.body.clientWidth / 2) - 250 + 'px';
        
        document.getElementById('users_shadow').style.width = screen.width + 'px';
        document.getElementById('users_shadow').style.height = screen.height + 'px';
        
        document.getElementById('users_shadow').style.display = 'block';
        document.getElementById('users_details').style.display = 'block';
        
        return 1;
    
    }
    
    // Edit user
    function Edit_User(user_id)
    {
    
        var ajax = new bull();
        var users_content = null;
        
        if (user_id === null || user_id <= 0)
            return 0;
        
        users_content = ajax.response('/cms/site/back_end/php/actions/edit_user.php', 
                                      'edit=1&user_id=' + user_id + '&lang_code=<?php echo $my_lang; ?>', 1);
        
        document.getElementById('users_details').innerHTML = users_content;
        
        document.getElementById('users_details').style.top = document.body.clientTop + 420 + 'px';
        document.getElementById('users_details').style.left = (document.body.clientWidth / 2) - 250 + 'px';
        
        document.getElementById('users_shadow').style.width = screen.width + 'px';
        document.getElementById('users_shadow').style.height = screen.height + 'px';
        
        document.getElementById('users_shadow').style.display = 'block';
        document.getElementById('users_details').style.display = 'block';
        
        return 1;
    
    }

    // Delete user
    function Delete_User(user_id)
    {
    
        var ajax = new bull();
        var users_content = null;
        
        if (user_id === null || user_id <= 0)
            return 0;
        
        users_content = ajax.response('/cms/site/back_end/php/actions/control/user_delete.php', 
                                      'delete=1&user_id=' + user_id + '&lang_code=<?php echo $my_lang; ?>', 1);
        
        document.getElementById('users_details').innerHTML = users_content;
        
        document.getElementById('users_details').style.top = document.body.clientTop + 420 + 'px';
        document.getElementById('users_details').style.left = (document.body.clientWidth / 2) - 250 + 'px';
        
        document.getElementById('users_shadow').style.width = screen.width + 'px';
        document.getElementById('users_shadow').style.height = screen.height + 'px';
        
        document.getElementById('users_shadow').style.display = 'block';
        document.getElementById('users_details').style.display = 'block';
        
        return 1;
    
    }
    
    // Insert new user
    function Insert_This_User()
    {
    
        var objects_values = new Array();
        var result = null;
        
        objects_values[0] = 'insert_username';
        objects_values[1] = 'insert_email';
        objects_values[2] = 'insert_type';
        objects_values[3] = 'insert_password';
        objects_values[4] = 'conf_password';
        
        result = Form_Validator('insert_user_form', objects_values);
        
        if (result === false)
            return 0;
        
        document.getElementById('admin_form_dhtml').submit();
        
        return 1;
    
    }
    
    // Update this user
    function Update_This_User(user_id)
    {
    
        var objects_values = new Array();
        var result = null;
        
        if (user_id === null || user_id <= 0)
            return 0;
        
        objects_values[0] = user_id;
        objects_values[1] = 'edit_username';
        objects_values[2] = 'edit_email';
        objects_values[3] = 'edit_type';
        objects_values[4] = 'edit_password';
        objects_values[5] = 'conf_password';
        
        result = Form_Validator('update_user_form', objects_values);
        
        if (result === false)
            return 0;
        
        document.getElementById('admin_form_dhtml').submit();
        
        return 1;
    
    }
    
    // Delete this user
    function Delete_This_User(user_id)
    {
    
        if (user_id === null || user_id <= 0)
            return 0;
        
        document.getElementById('del_user_id').value = user_id;
        
        document.getElementById('admin_form_dhtml').submit();
        
        return 1;
    
    }
    
    // Close user details
    function Close_User_Details()
    {
    
        document.getElementById('users_shadow').style.display = 'none';
        document.getElementById('users_details').style.display = 'none';
        
        return 1;
    
    }

</script>

<div class="class_content_area">
    <div id="users_area">
        <input id="del_user_id" name="del_user_id" type="hidden" value="" />
        <div id="table_controls">
            <div id="users_controls">
                <div class="class_records">
                    <?php echo ALPHA_CMS::Load_Content('records', 'content', $my_lang) . ' ' . $records[0][0]; ?>
                </div>
                <?php if ($_SESSION['ALPHA_CMS_USER_TYPE'] == 0): ?>
                <input id="new_user" onclick="New_User();" class="button" 
                       type="button" value="<?php echo ALPHA_CMS::Load_Content('new_user_label', 'content', $my_lang); ?>" />
                <?php else: ?>
                <input id="new_user" onclick="New_User();" class="button" style="color: #BFBFBF;" disabled 
                       type="button" value="<?php echo ALPHA_CMS::Load_Content('new_user_label', 'content', $my_lang); ?>" />
                <?php endif; ?>
                <?php
               
                    if ($records[0][0] > 0)
                        Search_Bar::Show();
                    
                    else
                        Search_Bar::Show(false);
                
                ?>
                <div id="sorting">
                    <div id="sort_label"><?php echo ALPHA_CMS::Load_Content('sort_label', 'content', $my_lang); ?>&nbsp;</div>
                    <?php
                    
                        if ($records[0][0] < 2)
                            echo '<select id="sort_type" name="sort_type" disabled>';
                        
                        else
                            echo '<select id="sort_type" name="sort_type" onchange="Do_Order();">';
                        
                        if (empty($_POST['sort_type']) || $_POST['sort_type'] == 'ASC')
                        {

                            echo '<option selected value="ASC">' . 
                                 ALPHA_CMS::Load_Content('asc_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="DESC">' . 
                                 ALPHA_CMS::Load_Content('desc_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['sort_type'] == 'DESC')
                        {

                            echo '<option value="ASC">' . 
                                 ALPHA_CMS::Load_Content('asc_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="DESC">' . 
                                 ALPHA_CMS::Load_Content('desc_label', 'content', $my_lang) . 
                                 '</option>';

                        }
                        
                        echo '</select>';
                    
                    ?>
                </div>
                <div id="ordering">
                    <div id="order_label"><?php echo ALPHA_CMS::Load_Content('order_label', 'content', $my_lang); ?>&nbsp;</div>
                    <?php
                    
                        if ($records[0][0] < 2)
                            echo '<select id="order_type" name="order_type" disabled>';
                        
                        else
                            echo '<select id="order_type" name="order_type" onchange="Do_Order();">';
                        
                        if (empty($_POST['order_type']) || $_POST['order_type'] == 'id')
                        {

                            echo '<option selected value="id">' . 
                                 ALPHA_CMS::Load_Content('id_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="username">' . 
                                 ALPHA_CMS::Load_Content('username_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="email">' . 
                                 ALPHA_CMS::Load_Content('email_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="type">' . 
                                 ALPHA_CMS::Load_Content('type_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'username')
                        {

                            echo '<option  value="id">' . 
                                 ALPHA_CMS::Load_Content('id_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="username">' . 
                                 ALPHA_CMS::Load_Content('username_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="email">' . 
                                 ALPHA_CMS::Load_Content('email_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="type">' . 
                                 ALPHA_CMS::Load_Content('type_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'email')
                        {

                            echo '<option  value="id">' . 
                                 ALPHA_CMS::Load_Content('id_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="username">' . 
                                 ALPHA_CMS::Load_Content('username_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="email">' . 
                                 ALPHA_CMS::Load_Content('email_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="type">' . 
                                 ALPHA_CMS::Load_Content('type_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'type')
                        {

                            echo '<option  value="id">' . 
                                 ALPHA_CMS::Load_Content('id_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="username">' . 
                                 ALPHA_CMS::Load_Content('username_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="email">' . 
                                 ALPHA_CMS::Load_Content('email_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="type">' . 
                                 ALPHA_CMS::Load_Content('type_label', 'content', $my_lang) . 
                                 '</option>';

                        }
                        
                        echo '</select>';
                    
                    ?>
                </div>
            </div>
        </div>
        <div id="users_content">
            <table id="users_table">
                <tr class="class_table_header">
                    <td><?php echo ALPHA_CMS::Load_Content('id_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('username_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('email_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('type_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('options_label', 'content', $my_lang); ?></td>
                </tr>
            <?php
            
                if (!empty($_POST['search_bar']))
                {
                
                    if (empty($_POST['order_type']) || empty($_POST['sort_type']))
                        $users = Search_Bar::Search('users', $_POST['search_bar']);
                    
                    else
                        $users = Search_Bar::Search('users', $_POST['search_bar'], $_POST['order_type'], $_POST['sort_type']);
                    
                    if (is_bool($users))
                        exit;
                    
                    if (empty($_SESSION['G_RESET_SEARCH']))
                    {
                    
                        Gutenberg('users', $users, 22, $_POST['offset'], 1);
                        
                        $_SESSION['G_RESET_SEARCH'] = 1;
                        $_SESSION['PREVIOUS_SEARCH_STR'] = $_POST['search_bar'];
                    
                    }
                    
                    else
                    {
                    
                        if ($_POST['search_bar'] != $_SESSION['PREVIOUS_SEARCH_STR'])
                            Gutenberg('users', $users, 22, $_POST['offset'], 1);
                        
                        else
                            Gutenberg('users', $users, 22, $_POST['offset']);
                        
                        $_SESSION['G_RESET_OFFSET'] = 1;
                        $_SESSION['PREVIOUS_SEARCH_STR'] = $_POST['search_bar'];
                    
                    }
                
                }
                
                else
                {
                
                    if (empty($_POST['order_type']) || empty($_POST['sort_type']))
                    {

                        $users = ALPHA_CMS::Execute_SQL_Command('SELECT `id`, `username`, `email`, `type` 
                                                                 FROM `alpha_users` 
                                                                 ORDER BY `id` ASC', 1);

                    }

                    else
                    {

                        $users = ALPHA_CMS::Execute_SQL_Command('SELECT `id`, `username`, `email`, `type` 
                                                                 FROM `alpha_users` 
                                                                 ORDER BY `' . $_POST['order_type'] . '` ' . $_POST['sort_type'], 1);

                    }
                    
                    if (is_bool($users))
                        exit;
                    
                    if (!empty($_SESSION['G_RESET_OFFSET']))
                    {
                    
                        Gutenberg('users', $users, 22, $_POST['offset'], 1);
                        
                        $_SESSION['G_RESET_OFFSET'] = 0;
                    
                    }
                    
                    else
                        Gutenberg('users', $users, 22, $_POST['offset']);
                    
                    $_SESSION['G_RESET_SEARCH'] = 0;
                
                }
            
            ?>
    </div>
    <div id="users_details"></div>
    <div id="users_shadow"></div>
</div>
