<?php

    /*
    
        GreyOS - ALPHA CMS
        
        Version: 10.0
        
        File name: admin_extensions.phtml
        Description: This file contains the admin extensions HTML.
        
        Coded by George Delaportas (G0D) & Konstantinos Gkoutzis (KGK)
        
        GreyOS
        Copyright © 2013
    
    */
    
    
    
    $my_lang = ALPHA_CMS::Get_Language();
    
    $records = 0;
    $exts = array();
    
    echo ALPHA_CMS::Load_Content('extensions_content', 'content', $my_lang);
    
    if (!empty($_POST['del_ext_name']) && !empty($_POST['del_ext_type']) && $_SESSION['ALPHA_CMS_USER'] == 'admin')
    {
    
        ALPHA_CMS::Delete_Extension($_POST['del_ext_name'], $_POST['del_ext_type']);
        
        $_POST['del_ext_name'] = 0;
        $_POST['del_ext_type'] = 0;
    
    }
    
    $files = ALPHA_CMS::Process_Dir(ALPHA_CMS::Absolute_Path('framework/extensions/'), true);
    
    foreach ($files as $file_name)
    {
    
        if (strstr($file_name['filename'], '.xml') && $file_name['filename'] != 'config.xml')
                $records++;
    
    }
    
    ALPHA_CMS::Load_Extension('search_bar', 'php');
    ALPHA_CMS::Load_Extension('ext_man', 'php');
    ALPHA_CMS::Load_Extension('gutenberg', 'php');

?>

<script type="text/javascript">

    // Order
    function Do_Order()
    {
    
        document.getElementById('admin_form_dhtml').submit();
        
        return 1;
    
    }
    
    // Edit extension
    function Edit_Extension(ext_name, ext_type)
    { 
    
        var ajax = new bull();
        var extensions_content = null;
        
        if (ext_name == null || ext_type == null || ext_name == '' || ext_type == '')
            return 0;
        
        extensions_content = ajax.response('/cms/site/back_end/php/actions/edit_extension.php', 
                                           'edit=1&extension_name=' + ext_name + 
                                           '&extension_type=' + ext_type + 
                                           '&lang_code=<?php echo $my_lang; ?>', 1);
        
        document.getElementById('extensions_details').innerHTML = extensions_content;
        
        document.getElementById('extensions_details').style.top = document.body.clientTop + 420 + 'px';
        document.getElementById('extensions_details').style.left = (document.body.clientWidth / 2) - 225 + 'px';
        
        document.getElementById('extensions_shadow').style.width = screen.width + 'px';
        document.getElementById('extensions_shadow').style.height = screen.height + 'px';
        
        document.getElementById('extensions_shadow').style.display = 'block';
        document.getElementById('extensions_details').style.display = 'block';
        
        return 1;
    
    }
    
    // Delete extension
    function Delete_Extension(ext_name, ext_type)
    {
    
        var ajax = new bull();
        var extensions_content = null;
        
        if (ext_name == null || ext_type == null || ext_name == '' || ext_type == '')
            return 0;
        
        extensions_content = ajax.response('/cms/site/back_end/php/actions/control/extension_delete.php', 
                                           'delete=1&extension_name=' + ext_name + 
                                           '&extension_type=' + ext_type + 
                                           '&lang_code=<?php echo $my_lang; ?>', 1);
        
        document.getElementById('extensions_details').innerHTML = extensions_content;
        
        document.getElementById('extensions_details').style.top = document.body.clientTop + 420 + 'px';
        document.getElementById('extensions_details').style.left = (document.body.clientWidth / 2) - 250 + 'px';
        
        document.getElementById('extensions_shadow').style.width = screen.width + 'px';
        document.getElementById('extensions_shadow').style.height = screen.height + 'px';
        
        document.getElementById('extensions_shadow').style.display = 'block';
        document.getElementById('extensions_details').style.display = 'block';
        
        return 1;
    
    }
    
    // Update this extension
    function Update_This_Ext(ext_name, ext_type)
    {
    
        var objects_values = new Array();
        var content = null;
        var all_elements = null;
        var result = null;
        var i = 0;
        
        content = document.getElementById('ext_form');
        
        all_elements = content.getElementsByTagName('input');
        
        objects_values[0] = ext_name;
        objects_values[1] = ext_type;
        objects_values[2] = 'status';
        objects_values[3] = 'protected';
        
        for (i = 2; i < all_elements.length; i++)
            objects_values[i + 2] = '&' + all_elements[i].id + '=' + all_elements[i].value;
        
        result = Form_Validator('update_ext_form', objects_values);
        
        if (result === false)
            return 0;
        
        document.getElementById('admin_form_dhtml').submit();
        
        return 1;
    
    }
    
    // Delete this extension
    function Delete_This_Ext(ext_name, ext_type)
    {
    
        document.getElementById('del_ext_name').value = ext_name;
        document.getElementById('del_ext_type').value = ext_type;
        
        document.getElementById('admin_form_dhtml').submit();
        
        return 1;
    
    }
    
    // Close extension details
    function Close_Ext_Details()
    {
    
        document.getElementById('extensions_shadow').style.display = 'none';
        document.getElementById('extensions_details').style.display = 'none';
        
        return 1;
    
    }

</script>

<div class="class_content_area">
    <div id="extensions_area">
        <input id="del_ext_name" name="del_ext_name" type="hidden" value="" />
        <input id="del_ext_type" name="del_ext_type" type="hidden" value="" />
        <div id="table_controls">
            <div id="extensions_controls">
                <div class="class_records">
                    <?php echo ALPHA_CMS::Load_Content('records', 'content', $my_lang) . ' ' . $records; ?>
                </div>
                <?php
               
                    if ($records > 0)
                        Search_Bar::Show();
                    
                    else
                        Search_Bar::Show(false);
                
                ?>
                <div id="sorting">
                    <div id="sort_label"><?php echo ALPHA_CMS::Load_Content('sort_label', 'content', $my_lang); ?>&nbsp;</div>
                    <?php
                    
                        if ($records < 2)
                            echo '<select id="sort_type" name="sort_type" disabled>';
                        
                        else
                            echo '<select id="sort_type" name="sort_type" onchange="Do_Order();">';
                        
                        if (empty($_POST['sort_type']) || $_POST['sort_type'] == 'ASC')
                        {

                            echo '<option selected value="ASC">' . 
                                 ALPHA_CMS::Load_Content('asc_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="DESC">' . 
                                 ALPHA_CMS::Load_Content('desc_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['sort_type'] == 'DESC')
                        {

                            echo '<option value="ASC">' . 
                                 ALPHA_CMS::Load_Content('asc_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="DESC">' . 
                                 ALPHA_CMS::Load_Content('desc_label', 'content', $my_lang) . 
                                 '</option>';

                        }
                        
                        echo '</select>';
                    
                    ?>
                </div>
                <div id="ordering">
                    <div id="order_label"><?php echo ALPHA_CMS::Load_Content('order_label', 'content', $my_lang); ?>&nbsp;</div>
                    <?php
                    
                        if ($records < 2)
                            echo '<select id="order_type" name="order_type" disabled>';
                        
                        else
                            echo '<select id="order_type" name="order_type" onchange="Do_Order();">';
                        
                        if (empty($_POST['order_type']) || $_POST['order_type'] == 'title')
                        {

                            echo '<option selected value="title">' . 
                                 ALPHA_CMS::Load_Content('ext_title_label', 'content', $my_lang) . 
                                 '</option>
                                  <option value="path">' . 
                                 ALPHA_CMS::Load_Content('path_label', 'content', $my_lang) . 
                                 '</option>
                                  <option value="type">' . 
                                 ALPHA_CMS::Load_Content('type_label', 'content', $my_lang) . 
                                 '</option>
                                  <option value="protected">' . 
                                 ALPHA_CMS::Load_Content('protected_label', 'content', $my_lang) .  
                                 '</option>
                                  <option value="status">' . 
                                 ALPHA_CMS::Load_Content('status_label', 'content', $my_lang) .  
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'path')
                        {

                            echo '<option value="title">' . 
                                 ALPHA_CMS::Load_Content('ext_title_label', 'content', $my_lang) . 
                                 '</option>
                                  <option selected value="path">' . 
                                 ALPHA_CMS::Load_Content('path_label', 'content', $my_lang) . 
                                 '</option>
                                  <option value="type">' . 
                                 ALPHA_CMS::Load_Content('type_label', 'content', $my_lang) . 
                                 '</option>
                                  <option value="protected">' . 
                                 ALPHA_CMS::Load_Content('protected_label', 'content', $my_lang) .  
                                 '</option>
                                  <option value="status">' . 
                                 ALPHA_CMS::Load_Content('status_label', 'content', $my_lang) .  
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'type')
                        {

                            echo '<option value="title">' . 
                                 ALPHA_CMS::Load_Content('ext_title_label', 'content', $my_lang) . 
                                 '</option>
                                  <option value="path">' . 
                                 ALPHA_CMS::Load_Content('path_label', 'content', $my_lang) . 
                                 '</option>
                                  <option selected value="type">' . 
                                 ALPHA_CMS::Load_Content('type_label', 'content', $my_lang) . 
                                 '</option>
                                  <option value="protected">' . 
                                 ALPHA_CMS::Load_Content('protected_label', 'content', $my_lang) .  
                                 '</option>
                                  <option value="status">' . 
                                 ALPHA_CMS::Load_Content('status_label', 'content', $my_lang) .  
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'protected')
                        {

                            echo '<option value="title">' . 
                                 ALPHA_CMS::Load_Content('ext_title_label', 'content', $my_lang) . 
                                 '</option>
                                  <option value="path">' . 
                                 ALPHA_CMS::Load_Content('path_label', 'content', $my_lang) . 
                                 '</option>
                                  <option value="type">' . 
                                 ALPHA_CMS::Load_Content('type_label', 'content', $my_lang) . 
                                 '</option>
                                  <option selected value="protected">' . 
                                 ALPHA_CMS::Load_Content('protected_label', 'content', $my_lang) .  
                                 '</option>
                                  <option value="status">' . 
                                 ALPHA_CMS::Load_Content('status_label', 'content', $my_lang) .  
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'status')
                        {

                            echo '<option value="title">' . 
                                 ALPHA_CMS::Load_Content('ext_title_label', 'content', $my_lang) . 
                                 '</option>
                                  <option value="path">' . 
                                 ALPHA_CMS::Load_Content('path_label', 'content', $my_lang) . 
                                 '</option>
                                  <option value="type">' . 
                                 ALPHA_CMS::Load_Content('type_label', 'content', $my_lang) . 
                                 '</option>
                                  <option value="protected">' . 
                                 ALPHA_CMS::Load_Content('protected_label', 'content', $my_lang) .  
                                 '</option>
                                  <option selected value="status">' . 
                                 ALPHA_CMS::Load_Content('status_label', 'content', $my_lang) .  
                                 '</option>';

                        }
                        
                        echo '</select>';
                    
                    ?>
                </div>
            </div>
        </div>
        <div id="extensions_content">
            <table id="extensions_table">
                <tr class="class_table_header">
                    <td><?php echo ALPHA_CMS::Load_Content('ext_title_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('path_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('type_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('protected_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('status_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('options_label', 'content', $my_lang); ?></td>
                </tr>
            <?php
            
                if (!empty($_POST['search_bar']))
                {
                
                    if (empty($_POST['order_type']) || empty($_POST['sort_type']))
                        $exts = Search_Bar::Search('ext', $_POST['search_bar']);
                    
                    else
                        $exts = Search_Bar::Search('ext', $_POST['search_bar'], $_POST['order_type'], $_POST['sort_type']);
                    
                    if (is_bool($exts))
                        exit;
                    
                    if (empty($_SESSION['G_RESET_SEARCH']))
                    {
                    
                        Gutenberg('extensions', $exts, 22, $_POST['offset'], 1);
                        
                        $_SESSION['G_RESET_SEARCH'] = 1;
                        $_SESSION['PREVIOUS_SEARCH_STR'] = $_POST['search_bar'];
                    
                    }
                    
                    else
                    {
                    
                        if ($_POST['search_bar'] != $_SESSION['PREVIOUS_SEARCH_STR'])
                            Gutenberg('extensions', $exts, 22, $_POST['offset'], 1);
                        
                        else
                            Gutenberg('extensions', $exts, 22, $_POST['offset']);
                        
                        $_SESSION['G_RESET_OFFSET'] = 1;
                        $_SESSION['PREVIOUS_SEARCH_STR'] = $_POST['search_bar'];
                    
                    }
                
                }
                
                else
                {
                
                    if (empty($_POST['order_type']) || empty($_POST['sort_type']))
                    {
                    
                        $exts = Show_Extensions(ALPHA_CMS::Absolute_Path('framework/extensions/'), 'php', 'title', 'ASC');
                        $exts = array_merge($exts, Show_Extensions(ALPHA_CMS::Absolute_Path('framework/extensions/'), 'js', 'title', 'ASC'));
                        $exts = array_merge($exts, Show_Extensions(ALPHA_CMS::Absolute_Path('framework/extensions/'), 'ajax', 'title', 'ASC'));
                    
                    }
                    
                    else
                    {
                    
                        $exts = Show_Extensions(ALPHA_CMS::Absolute_Path('framework/extensions/'), 'php', $_POST['order_type'], $_POST['sort_type']);
                        $exts = array_merge($exts, Show_Extensions(ALPHA_CMS::Absolute_Path('framework/extensions/'), 'js', $_POST['order_type'], $_POST['sort_type']));
                        $exts = array_merge($exts, Show_Extensions(ALPHA_CMS::Absolute_Path('framework/extensions/'), 'ajax', $_POST['order_type'], $_POST['sort_type']));
                    
                    }
                    
                    if (is_bool($exts))
                        exit;
                    
                    if (!empty($_SESSION['G_RESET_OFFSET']))
                    {
                    
                        Gutenberg('extensions', $exts, 22, $_POST['offset'], 1);
                        
                        $_SESSION['G_RESET_OFFSET'] = 0;
                    
                    }
                    
                    else
                        Gutenberg('extensions', $exts, 22, $_POST['offset']);
                    
                    $_SESSION['G_RESET_SEARCH'] = 0;
                
                }
            
            ?>
    </div>
    <div id="extensions_details"></div>
    <div id="extensions_shadow"></div>
</div>
