<?php

    /*
    
        GreyOS - ALPHA CMS
        
        Version: 10.0
        
        File name: admin_logs.phtml
        Description: This file contains the admin logs HTML.
        
        Coded by George Delaportas (G0D)
        
        GreyOS
        Copyright © 2013
    
    */
    
    
    
    $my_lang = ALPHA_CMS::Get_Language();
    
    $logs = array();
    $records = array();
    
    echo ALPHA_CMS::Load_Content('logs_content', 'content', $my_lang);
    
    if (!empty($_POST['del_log_id']) && $_SESSION['ALPHA_CMS_USER'] == 'admin')
    {
    
        ALPHA_CMS::Delete_Log($_POST['del_log_id']);
        
        $_POST['del_log_id'] = null;
    
    }
    
    $logs = ALPHA_CMS::Show_Log('*');
    
    $records = ALPHA_CMS::Execute_SQL_Command('SELECT COUNT(*) 
                                               FROM `alpha_logs`', 1);
    
    ALPHA_CMS::Load_Extension('search_bar', 'php');
    ALPHA_CMS::Load_Extension('gutenberg', 'php');

?>

<script type="text/javascript">

    // Order
    function Do_Order()
    {
    
        document.getElementById('admin_form_dhtml').submit();
        
        return 1;
    
    }

    // Show log details
    function Show_Log_Details(log_id)
    {
    
        var ajax = new bull();
        var logs_content = null;
        
        if (log_id === null || log_id <= 0)
            return 0;
        
        logs_content = ajax.response('/cms/site/back_end/php/actions/log_details.php', 
                                     'logs=1&log_id=' + log_id + '&lang_code=<?php echo $my_lang; ?>', 1);
        
        document.getElementById('logs_details').innerHTML = logs_content;
        
        document.getElementById('logs_details').style.top = document.body.clientTop + 420 + 'px';
        document.getElementById('logs_details').style.left = (document.body.clientWidth / 2) - 250 + 'px';
        
        document.getElementById('logs_shadow').style.width = screen.width + 'px';
        document.getElementById('logs_shadow').style.height = screen.height + 'px';
        
        document.getElementById('logs_shadow').style.display = 'block';
        document.getElementById('logs_details').style.display = 'block';
        
        return 1;
    
    }
    
    // Delete logs
    function Delete_Logs()
    {
    
        var ajax = new bull();
        var logs_content = null;
        
        logs_content = ajax.response('/cms/site/back_end/php/actions/control/log_delete.php', 
                                     'delete=1&lang_code=<?php echo $my_lang; ?>', 1);
        
        document.getElementById('logs_details').innerHTML = logs_content;
        
        document.getElementById('logs_details').style.top = document.body.clientTop + 420 + 'px';
        document.getElementById('logs_details').style.left = (document.body.clientWidth / 2) - 250 + 'px';
        
        document.getElementById('logs_shadow').style.width = screen.width + 'px';
        document.getElementById('logs_shadow').style.height = screen.height + 'px';
        
        document.getElementById('logs_shadow').style.display = 'block';
        document.getElementById('logs_details').style.display = 'block';
        
        return 1;
    
    }
    
    // Delete all logs
    function Delete_All_Logs()
    {
    
        document.getElementById('del_log_id').value = '*';
        
        document.getElementById('admin_form_dhtml').submit();
        
        return 1;
    
    }
    
    // Close log details
    function Close_Log_Details()
    {
    
        document.getElementById('logs_shadow').style.display = 'none';
        document.getElementById('logs_details').style.display = 'none';
        
        return 1;
    
    }

</script>

<div class="class_content_area">
    <div id="logs_area">
        <input id="del_log_id" name="del_log_id" type="hidden" value="" />
        <div id="table_controls">
            <div id="logs_controls">
                <div class="class_records">
                    <?php echo ALPHA_CMS::Load_Content('records', 'content', $my_lang) . ' ' . $records[0][0]; ?>
                </div>
                <?php if ($_SESSION['ALPHA_CMS_USER'] == 'admin' && !empty($logs)): ?>
                <input id="del_logs" onclick="Delete_Logs();" class="button" 
                       type="button" value="<?php echo ALPHA_CMS::Load_Content('del_logs_label', 'content', $my_lang); ?>" />
                <?php else: ?>
                <input id="del_logs" class="button" style="color: #BFBFBF;" disabled 
                       type="button" value="<?php echo ALPHA_CMS::Load_Content('del_logs_label', 'content', $my_lang); ?>" />
                <?php endif; ?>
                <?php
               
                    if ($records[0][0] > 0)
                        Search_Bar::Show();
                    
                    else
                        Search_Bar::Show(false);
                
                ?>
                <div id="sorting">
                    <div id="sort_label"><?php echo ALPHA_CMS::Load_Content('sort_label', 'content', $my_lang); ?>&nbsp;</div>
                    <?php
                    
                        if ($records[0][0] < 2)
                            echo '<select id="sort_type" name="sort_type" disabled>';
                        
                        else
                            echo '<select id="sort_type" name="sort_type" onchange="Do_Order();">';
                        
                        if (empty($_POST['sort_type']) || $_POST['sort_type'] == 'ASC')
                        {

                            echo '<option selected value="ASC">' . 
                                 ALPHA_CMS::Load_Content('asc_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="DESC">' . 
                                 ALPHA_CMS::Load_Content('desc_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['sort_type'] == 'DESC')
                        {

                            echo '<option value="ASC">' . 
                                 ALPHA_CMS::Load_Content('asc_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="DESC">' . 
                                 ALPHA_CMS::Load_Content('desc_label', 'content', $my_lang) . 
                                 '</option>';

                        }
                        
                        echo '</select>';
                    
                    ?>
                </div>
                <div id="ordering">
                    <div id="order_label"><?php echo ALPHA_CMS::Load_Content('order_label', 'content', $my_lang); ?>&nbsp;</div>
                    <?php
                    
                        if ($records[0][0] < 2)
                            echo '<select id="order_type" name="order_type" disabled>';
                        
                        else
                            echo '<select id="order_type" name="order_type" onchange="Do_Order();">';
                        
                        if (empty($_POST['order_type']) || $_POST['order_type'] == 'id')
                        {

                            echo '<option selected value="id">' . 
                                 ALPHA_CMS::Load_Content('id_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="entity">' . 
                                 ALPHA_CMS::Load_Content('entity_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="error_code">' . 
                                 ALPHA_CMS::Load_Content('error_code_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="message">' . 
                                 ALPHA_CMS::Load_Content('error_msg_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="file">' . 
                                 ALPHA_CMS::Load_Content('file_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="line">' . 
                                 ALPHA_CMS::Load_Content('line_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="date_time">' . 
                                 ALPHA_CMS::Load_Content('date_time_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'entity')
                        {

                            echo '<option value="id">' . 
                                 ALPHA_CMS::Load_Content('id_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="entity">' . 
                                 ALPHA_CMS::Load_Content('entity_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="error_code">' . 
                                 ALPHA_CMS::Load_Content('error_code_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="message">' . 
                                 ALPHA_CMS::Load_Content('error_msg_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="file">' . 
                                 ALPHA_CMS::Load_Content('file_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="line">' . 
                                 ALPHA_CMS::Load_Content('line_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="date_time">' . 
                                 ALPHA_CMS::Load_Content('date_time_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'error_code')
                        {

                            echo '<option value="id">' . 
                                 ALPHA_CMS::Load_Content('id_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="entity">' . 
                                 ALPHA_CMS::Load_Content('entity_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="error_code">' . 
                                 ALPHA_CMS::Load_Content('error_code_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="message">' . 
                                 ALPHA_CMS::Load_Content('error_msg_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="file">' . 
                                 ALPHA_CMS::Load_Content('file_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="line">' . 
                                 ALPHA_CMS::Load_Content('line_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="date_time">' . 
                                 ALPHA_CMS::Load_Content('date_time_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'message')
                        {

                            echo '<option value="id">' . 
                                 ALPHA_CMS::Load_Content('id_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="entity">' . 
                                 ALPHA_CMS::Load_Content('entity_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="error_code">' . 
                                 ALPHA_CMS::Load_Content('error_code_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="message">' . 
                                 ALPHA_CMS::Load_Content('error_msg_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="file">' . 
                                 ALPHA_CMS::Load_Content('file_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="line">' . 
                                 ALPHA_CMS::Load_Content('line_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="date_time">' . 
                                 ALPHA_CMS::Load_Content('date_time_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'file')
                        {

                            echo '<option value="id">' . 
                                 ALPHA_CMS::Load_Content('id_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="entity">' . 
                                 ALPHA_CMS::Load_Content('entity_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="error_code">' . 
                                 ALPHA_CMS::Load_Content('error_code_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="message">' . 
                                 ALPHA_CMS::Load_Content('error_msg_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="file">' . 
                                 ALPHA_CMS::Load_Content('file_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="line">' . 
                                 ALPHA_CMS::Load_Content('line_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="date_time">' . 
                                 ALPHA_CMS::Load_Content('date_time_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'line')
                        {

                            echo '<option value="id">' . 
                                 ALPHA_CMS::Load_Content('id_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="entity">' . 
                                 ALPHA_CMS::Load_Content('entity_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="error_code">' . 
                                 ALPHA_CMS::Load_Content('error_code_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="message">' . 
                                 ALPHA_CMS::Load_Content('error_msg_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="file">' . 
                                 ALPHA_CMS::Load_Content('file_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="line">' . 
                                 ALPHA_CMS::Load_Content('line_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="date_time">' . 
                                 ALPHA_CMS::Load_Content('date_time_label', 'content', $my_lang) . 
                                 '</option>';

                        }

                        elseif ($_POST['order_type'] == 'date_time')
                        {

                            echo '<option value="id">' . 
                                 ALPHA_CMS::Load_Content('id_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="entity">' . 
                                 ALPHA_CMS::Load_Content('entity_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="error_code">' . 
                                 ALPHA_CMS::Load_Content('error_code_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="message">' . 
                                 ALPHA_CMS::Load_Content('error_msg_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="file">' . 
                                 ALPHA_CMS::Load_Content('file_label', 'content', $my_lang) . 
                                 '</option>
                                 <option value="line">' . 
                                 ALPHA_CMS::Load_Content('line_label', 'content', $my_lang) . 
                                 '</option>
                                 <option selected value="date_time">' . 
                                 ALPHA_CMS::Load_Content('date_time_label', 'content', $my_lang) . 
                                 '</option>';

                        }
                        
                        echo '</select>';
                    
                    ?>
                </div>
            </div>
        </div>
        <div id="logs_content">
            <table id="logs_table">
                <tr class="class_table_header">
                    <td><?php echo ALPHA_CMS::Load_Content('id_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('entity_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('error_code_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('error_msg_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('file_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('line_label', 'content', $my_lang); ?></td>
                    <td><?php echo ALPHA_CMS::Load_Content('date_time_label', 'content', $my_lang); ?></td>
                </tr>
            <?php
            
                if (!empty($_POST['search_bar']))
                {
                
                    if (empty($_POST['order_type']) || empty($_POST['sort_type']))
                        $logs = Search_Bar::Search('logs', $_POST['search_bar']);
                    
                    else
                        $logs = Search_Bar::Search('logs', $_POST['search_bar'], $_POST['order_type'], $_POST['sort_type']);
                    
                    if (is_bool($logs))
                        exit;
                    
                    if (empty($_SESSION['G_RESET_SEARCH']))
                    {
                    
                        Gutenberg('logs', $logs, 22, $_POST['offset'], 1);
                        
                        $_SESSION['G_RESET_SEARCH'] = 1;
                        $_SESSION['PREVIOUS_SEARCH_STR'] = $_POST['search_bar'];
                    
                    }
                    
                    else
                    {
                    
                        if ($_POST['search_bar'] != $_SESSION['PREVIOUS_SEARCH_STR'])
                            Gutenberg('logs', $logs, 22, $_POST['offset'], 1);
                        
                        else
                            Gutenberg('logs', $logs, 22, $_POST['offset']);
                        
                        $_SESSION['G_RESET_OFFSET'] = 1;
                        $_SESSION['PREVIOUS_SEARCH_STR'] = $_POST['search_bar'];
                    
                    }
                
                }
                
                else
                {
                
                    if (empty($_POST['order_type']) || empty($_POST['sort_type']))
                        $logs = ALPHA_CMS::Show_Log('*');

                    else
                        $logs = ALPHA_CMS::Show_Log('*', '*', $_POST['order_type'], $_POST['sort_type']);
                    
                    if (is_bool($logs))
                        exit;
                    
                    if (!empty($_SESSION['G_RESET_OFFSET']))
                    {
                    
                        Gutenberg('logs', $logs, 22, $_POST['offset'], 1);
                        
                        $_SESSION['G_RESET_OFFSET'] = 0;
                    
                    }
                    
                    else
                        Gutenberg('logs', $logs, 22, $_POST['offset']);
                    
                    $_SESSION['G_RESET_SEARCH'] = 0;
                
                }
            
            ?>
    </div>
    <div id="logs_details"></div>
    <div id="logs_shadow"></div>
</div>
