<?php

    /*
    
        GreyOS - ALPHA CMS
        
        Version: 10.0
        
        File name: admin_dashboard.phtml
        Description: This file contains the admin dashboard HTML.
        
        Coded by George Delaportas (G0D)
        
        GreyOS
        Copyright © 2013
    
    */
    
    
    
    $my_lang = ALPHA_CMS::Get_Language();
    
    echo ALPHA_CMS::Load_Content('dashboard_content', 'content', $my_lang);

?>



    <div id="dynamic_pane" class="class_content_area">
        
    </div>
