<div id="top_panel">
    <div id="top_area">
        <div id="logo">
            <div id="version">3.0 (alpha)</div> <!-- To be set automatically in the future... -->
        </div>
        <div id="user_profile"></div>
        <div id="clock"></div>
        <div id="audio"></div>
        <div id="device_manager"></div>
        <div id="services_tray"></div>
    </div>
    <div id="bottom_area">
        <div id="action_icons"></div>
        <div id="dynamic_container">
            <div id="favorite_apps"></div>
            <div id="search">
                <div id="eye" title="Philos :: Your personal assistant!"></div>
                <div id="eureka">
                    <input id="eureka_search_box" type="text" value="" placeholder="What's next?">
                </div>
            </div>
        </div>
    </div>
</div>
<div id="desktop"></div>
<!--<div id="xmass"></div>-->
