<div id="top_panel">
    <div id="logo">
        <div id="version"></div>
    </div>
    <div id="user_profile"></div>
    <div id="clock"></div>
    <div id="audio"></div>
    <div id="device_manager"></div>
    <div id="services_tray"></div>
    <div id="action_icons"></div>
    <div id="favorite_apps"></div>
</div>
<div id="desktop"></div>
<video id="bg_video" autoplay loop poster="/site/themes/morph/pix/wallpaper.png">
    <source src="/site/themes/morph/pix/wallpaper_animated.mp4" type="video/mp4">
</video>
<!--<div id="xmas"></div>-->
