<div id="top_panel">
    <div id="top_area">
        <div id="logo"></div>
        <div id="user_profile"></div>
        <div id="clock"></div>
    </div>
    <div id="bottom_area">
        <div id="action_icons"></div>
        <div id="dynamic_container">
            <div id="favorite_apps"></div>
            <div id="eureka">
                <!--
                <div id="eye" title="Philos :: Your personal assistant!"></div>
                <div id="search_area">
                    <input id="eureka_search_box" type="text" value="" placeholder="What's next?">
                </div>
                -->
            </div>
        </div>
    </div>
</div>
<div id="desktop"></div>
<!--
<audio autoplay>
    <source src="/site/themes/tomorrow/sounds/login.mp3" type="audio/mpeg">
</audio>
<audio id="button_sound">
    <source src="/site/themes/tomorrow/sounds/button_click.mp3" type="audio/mpeg">
</audio>
<audio id="pong_sound">
    <source src="/site/themes/tomorrow/sounds/pong.wav" type="audio/mpeg">
</audio>
-->