<?php
    UTIL::Load_Extension('vulcan', 'js');
    UTIL::Load_Extension('jap', 'js');
    UTIL::Load_Extension('bull', 'js');
    UTIL::Load_Extension('sensei', 'js');
    UTIL::Load_Extension('stopwatch', 'js');
    UTIL::Load_Extension('heartbeat', 'js');
    UTIL::Load_Extension('msgbox', 'js');
    UTIL::Load_Extension('workbox', 'js');
    UTIL::Load_Extension('key_manager', 'js');
    UTIL::Load_Extension('ajax_factory', 'js');
    UTIL::Load_Extension('content_fetcher', 'js');
    UTIL::Load_Extension('ultron', 'js');
    UTIL::Load_Extension('splash', 'php');
    UTIL::Load_Extension('keycard', 'php');
    UTIL::Load_Extension('regy', 'php');
    UTIL::Load_Extension('ra', 'php');

    if (!empty($_POST))
    {
        $post_data = $_POST;

        $_POST = null;
    }

    // Uncomment to test the RA ORM (MySQL or MSSQL running service is required)
    /*
    $RA = new RA();
    $result = $RA::ORM('my')
              ->Initialize('root', '', 'localhost')
              ->Use_DB_Model('test_odb')
              ->Save_DB()
              ->Use_Table_Model('test_table_1')
              ->New_Model_Property('Surname', 'Smith')
              ->Delete_Model_Property('name')
              ->Save_Table('test_table_1')
              ->Use_Table_Model('test_table_2')
              ->New_Model_Property('Surname', 'Stalone')
              ->Edit_Model_Property('Surname', 'Statham')
              ->Save_Table('test_table_2')
              ->Result();
    */
?>
            <div id="test" class="page">
                <div class="content">
                    <?
                        UTIL::Load_Content('test', 'dynamic');

                        echo '<br><br>';
                        echo MVC::Restore_Content('test');
                    ?>
                    <div class="controls">
                        <div id="test_data">
                            <br>
                            <div id="test_elements">
                                <?
                                    $splash = new SPLASH();

                                    $test_text = UTIL::Load_Content('test_button_text', 'static');

                                    echo '<div id="left_elements">';
                                    echo '<div class="control_item">';
                                    echo $splash->Button('create', array('value'    =>  $test_text . ' (AJAX request)',
                                                                         'type'     =>  'button',
                                                                         'class'    =>  'button button_alt'),
                                                                   array('onclick'  => 'ajax_fetch_content(\'motto\')'));
                                    echo '</div>';
                                    //print_r($splash->Button('debug', array('value', 'id'), array('onclick')));

                                    echo '<div class="control_item">';
                                    echo $splash->Button('create', array('value'    =>  $test_text . ' (AJAX response)',
                                                                         'type'     =>  'button',
                                                                         'class'    =>  'button button_alt'),
                                                                   array('onajaxserverclick'   => 
                                                                   array('Server_Mouse_Click(Hello micro-MVC! (AJAX))', 
                                                                         'test_results')));
                                    echo '</div>';
                                    //print_r($splash->Button('debug', array('value', 'id'), array('onajaxserverclick')));

                                    echo '<div class="control_item">';
                                    echo $splash->Button('create', array('value'    =>  $test_text . ' (Form post)',
                                                                         'type'     =>  'button',
                                                                         'class'    =>  'button button_alt'),
                                                                   array('onserverclick'        => 
                                                                   array('Server_Mouse_Click(Hello micro-MVC! (Form post))', 
                                                                         '../test/')));
                                    echo '</div>';
                                    //print_r($splash->Button('debug', array('value', 'id'), array('onserverclick')));

                                    echo '<br><div class="control_item">';
                                    echo $splash->Button('create', array('value'    =>  $test_text . ' (Login form)',
                                                                         'type'     =>  'button',
                                                                         'class'    =>  'button button_alt'),
                                                                   array('onclick'  =>  'show_login_box()'));
                                    echo '</div>';
                                    //print_r($splash->Button('debug', array('value', 'id'), array('onclick')));

                                    echo '<div class="control_item">';
                                    echo $splash->Button('create', array('value'    =>  $test_text . ' (Registration form)',
                                                                         'type'     =>  'button',
                                                                         'class'    =>  'button button_alt'),
                                                                   array('onclick'  =>  'show_register_box()'));
                                    echo '</div>';
                                    //print_r($splash->Button('debug', array('value', 'id'), array('onclick')));
                                    echo '</div>';

                                    echo '<div id="right_elements">';
                                    echo '<div class="control_item">
                                          <input id="file_input" name="file" type="file" class="button" required>
                                          </div>';
                                    echo '<div class="control_item" style="margin-bottom: 44px;">';
                                    echo $splash->Button('create', array('value'    =>  $test_text . ' (AJAX file post)',
                                                                         'type'     =>  'button',
                                                                         'class'    =>  'button'),
                                                                   array('onclick'  =>  'send_data_to_server()'));
                                    echo '</div>';
                                    //print_r($splash->Button('debug', array('value', 'id'), array('onclick')));

                                    echo '<br><div class="control_item">';
                                    echo $splash->Button('create', array('value'    =>  $test_text . ' (Logout button)',
                                                                         'type'     =>  'button',
                                                                         'class'    =>  'button button_alt'),
                                                                   array('onclick'  =>  'logout()'));
                                    echo '</div>';
                                    //print_r($splash->Button('debug', array('value', 'id'), array('onclick')));

                                    echo '<div class="control_item">';
                                    echo $splash->Button('create', array('value'    =>  $test_text . ' (Send email)',
                                                                         'type'     =>  'button',
                                                                         'class'    =>  'button button_alt'),
                                                                   array('onclick'  =>  'send_email()'));
                                    echo '</div>';
                                    //print_r($splash->Button('debug', array('value', 'id'), array('onclick')));
                                    echo '</div>';
                                ?>
                            </div>
                            <br>
                            <div id="test_results" class="note">
                            <?
                                if (isset($post_data))
                                {
                                    if (!empty($post_data['splash_post_result']))
                                        echo $post_data['splash_post_result'];
                                    else
                                    {
                                        $searches = array('{message}');
                                        $replaces = array(print_r($post_data, true));
                                        $arguments = array($searches, $replaces);
                                        $info_template = UTIL::Fetch_Template('info', $arguments);

                                        echo $info_template;
                                    }
                                }
                            ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

<script>
    var dom = new vulcan();
    var ajax = new bull();
    var work_box = new workbox();
    var key_card = new keycard();
    var regy_form = new regy();

    work_box.init('main', 'micro-MVC', 'Close');

    function ajax_fetch_content(content_id)
    {
        var msg_box = new msgbox();

        msg_box.init('main');

        content_fetcher(content_id, '<?=LANG::Get('this');?>', function(response) { msg_box.show('micro-MVC', response); });
    }

    function send_data_to_server()
    {
        var file_input_element = dom.objects.by_id('file_input');
        var form_data = new FormData();

        form_data.append('test_file', file_input_element.files[0]);

        var ajax_config = {
                                "type"                  :   "data",
                                "url"                   :   "/framework/mvc/views/assets/php/ajax_test.php",
                                "data"                  :   form_data,
                                "element_id"            :   "test_results",
                                "content_fill_mode"     :   "replace"
                          };

        ajax.run(ajax_config);
    }

    <?
        if (!isset($post_data))
        {
    ?>
            var ajax_config = {
                                    "type"                  :   "data",
                                    "url"                   :   "/framework/mvc/views/assets/php/ajax_test.php",
                                    "data"                  :   "ajax_check=1",
                                    "element_id"            :   "test_results",
                                    "content_fill_mode"     :   "replace"
                              };

            ajax.run(ajax_config);
    <?
        }

        unset($post_data);
    ?>

    function show_login_box()
    {
        var login_form = '<?=KeyCard::Show_Login_Form();?>';

        blur_screen('show');

        work_box.show(login_form, null, function() { blur_screen('hide'); });

        key_card.init('login');
    }

    function show_register_box()
    {
        var register_form = '<?=Regy::Show_Form();?>';

        blur_screen('show');

        work_box.show(register_form, null, function() { blur_screen('hide'); });

        regy_form.init();
    }

    function logout()
    {
        var logout_button = '<?=KeyCard::Show_Logout_Button();?>';

        blur_screen('show');

        work_box.show(logout_button, null, function() { blur_screen('hide'); });

        key_card.init('logout');
    }

    function send_email()
    {
        var data = 'gate=send_email&send=1&email=test@testdomain.com';

        ajax_factory(data, function(response)
                           {
                                dom.objects.by_id('test_results').innerHTML = response;

                                console.log('[Woody response]')
                                console.log('OK');
                                console.log('');
                           },
                           function()
                           {
                                // Nothing to do...
                           },
                           function()
                           {
                                // Nothing to do...
                           });
    }

    // Use this function when logged-in to avoid session hijacking or utilize Anti-Hijack extension straight from PHP
    function hijack_protection()
    {
        var data = 'gate=hijack_protection';

        ajax_factory(data, function(response)
                           {
                                console.log('[Anti-Hijack response]')
                                console.log(response);
                                console.log('');
                           },
                           function()
                           {
                                location.assign('/');
                           },
                           function()
                           {
                               // Nothing to do...
                           });
    }

    function blur_screen(mode)
    {
        var main_body = dom.objects.by_id('test');

        if (mode === 'show')
            main_body.style.filter = 'blur(8px)';
        else
            main_body.style.filter = 'none';
    }

    dom.system.require('/framework/mvc/views/assets/js', 'test');
</script>
